/*
 * Copyright 2026 ekwongchum
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.ekwong.mailcleaner.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.tags.Tag;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * OpenAPI metadata for the mail-cleaner REST API. Endpoint schemas are generated by springdoc from
 * the controllers and served at {@code /v3/api-docs} and {@code /swagger-ui.html}.
 */
@Configuration
public class OpenApiConfig {

    @Bean
    public OpenAPI mailCleanerOpenApi() {
        return new OpenAPI()
                .info(
                        new Info()
                                .title("mail-cleaner API")
                                .version("1.2.0")
                                .description(
                                        "Consumes mail_meta_topic notifications, reads the email from object storage, "
                                                + "and indexes its metadata into the Elasticsearch mail_info index. The HTTP "
                                                + "endpoints batch-delete documents from the index by id and download the "
                                                + "original email as .eml from object storage."))
                .tags(
                        java.util.List.of(
                                new Tag()
                                        .name("Mail info management")
                                        .description(
                                                "Manage archived emails: delete Elasticsearch "
                                                        + "mail_info documents and download original "
                                                        + ".eml content from object storage")));
    }
}
