/*
 * Copyright 2026 ekwongchum
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.ekwong.journalarchiver.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.tags.Tag;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * OpenAPI metadata for the journal-archiver REST API. Endpoint schemas are generated by springdoc
 * from the controllers and served at {@code /v3/api-docs} and {@code /swagger-ui.html}.
 */
@Configuration
public class OpenApiConfig {

    @Bean
    public OpenAPI journalArchiverOpenApi() {
        return new OpenAPI()
                .info(
                        new Info()
                                .title("journal-archiver API")
                                .version("1.0.0")
                                .description(
                                        "Receives journal emails via embedded SMTP, archives metadata into MongoDB, "
                                                + "raw email into S3, and publishes notifications to RocketMQ. The HTTP endpoint "
                                                + "re-publishes notifications for archived emails."))
                .tags(
                        java.util.List.of(
                                new Tag()
                                        .name("Notification resend")
                                        .description(
                                                "Re-publish mail_meta_topic notifications for archived emails")));
    }
}
